### ISSUE TITLE
Calculate all the bytes needed in a function?

### ISSUE THREAD

**Issue by Vghxv** [garry911128/mini-python#17]

**Comment by garry911128** [comment]
i think its needed, 我在寫HW1的組語時，就蠻常遇到字節跟指令不相符的問題，但是我是組語智障

btw，你不是有做rbp的堆疊回復與去除

**Comment by Vghxv** [comment]
> 我在寫HW1的組語時，就蠻常遇到字節跟指令不相符的問題，

wdum

> 你不是有做rbp的堆疊回復與去除

yes

**Comment by garry911128** [comment]
比如說浮點數跟整數的字節不一樣，在運算的時後應該就要保持住吧

**Comment by Vghxv** [comment]
done
